controller_joint_names: ['', 'right_wheel_hinge', 'left_wheel_hinge', 'swivel_FR_hinge', 'castor_FR_hinge', 'swivel_FL_hinge', 'castor_FL_hinge', 'swivel_BR_hinge', 'castor_BR_hinge', 'swivel_BL_hinge', 'castor_BL_hinge', ]
